### PR TITLE
Imgui test

### PR DESCRIPTION
**Pull request by TimotheeDurand**
added ImGui support + example main.

### CODE REVIEW

**Review by Raul6469 — CHANGES_REQUESTED** [review]
what is `main.cpp.backup`?

Also, you should merge master in your branch to trigger the builds

**Comment by TimotheeDurand** [comment]
@Raul6469 main.cpp.backup is a backup of the old main (who would have guessed 😄)
care to explain why the hell do i need to merge master in my branch ? Isn't the whole purpose of a pull request to do avoid this kind of hassle ?

**Comment by TimotheeDurand** [comment]
nvm i'm retarded

**Comment by Raul6469** [comment]
@TimotheeDurand The purpose of a pull request is mainly for discussion and code review. Requiring the feature branch to be up to date with master can be useful to ensure that the latest changes are tested.

**Review by Raul6469 — CHANGES_REQUESTED** [review]
Please delete `main.cpp.backup`. Git already keeps history, there is no need to keep file versioning in our repository

**Review by Raul6469 — APPROVED** [review]

**Pull request merged**
